# keywords.py

# Ключевые слова для категории "sketch"
sketch_keywords = [
    "sketch", "эскиз", "drawing", "рисунок", "draft", "набросок", "outline",
    "контур", "doodle", "карандаш", "pencil", "черновик", "concept", "концепт",
    "design", "дизайн", "idea", "идея", "rough", "грубый", "preliminary",
    "предварительный", "mockup", "макет", "blueprint", "чертеж", "plan",
    "план", "artwork", "арт", "illustration", "иллюстрация", "pen", "ручка",
    "ink sketch", "чернильный эскиз", "initial", "первоначальный", "layout",
    "макет", "pattern", "узор", "lineart", "линейный рисунок", "wip sketch",
    "эскиз в процессе", "drafting", "черчение", "preparation", "подготовка",
    "study", "этюд", "practice", "практика", "test draw", "пробный рисунок",
    "sketchbook", "скетчбук", "hand-drawn", "ручной рисунок", "concept art",
    "концепт-арт", "visual idea", "визуальная идея", "drawing plan",
    "план рисунка", "prelim sketch", "предварительный эскиз", "art draft",
    "арт-черновик", "early design", "ранний дизайн"
]

# Ключевые слова для категории "tattoo"
tattoo_keywords = [
    "tattoo", "тату", "ink", "чернила", "needle", "игла", "fresh ink",
    "свежая тату", "new tattoo", "новая тату", "tat", "татуировка",
    "permanent", "перманент", "body art", "боди-арт", "skin art",
    "искусство на коже", "finished tattoo", "готовая тату", "complete tattoo",
    "завершённая тату", "done", "готово", "final result",
    "финальный результат", "fresh tat", "свежая татуировка", "healed tattoo",
    "залеченная тату", "inked", "зачернённый", "tattooed", "татуированный",
    "art on skin", "арт на коже", "design on skin", "дизайн на коже", "piece",
    "работа", "masterpiece", "шедевр", "tattoo art", "тату-арт",
    "freshly inked", "только что зачернённый", "new ink", "новые чернила",
    "tattoo reveal", "показ тату", "tat reveal", "раскрытие тату",
    "final tattoo", "финальная тату", "inked up", "зачернённый",
    "tattoo session done", "сеанс тату завершён", "tattoo finished",
    "тату закончена", "my work", "моя работа", "client tattoo", "тату клиента",
    "fresh design", "свежий дизайн"
]

# Ключевые слова для категории "in_progress"
in_progress_keywords = [
    "in progress", "в процессе", "wip", "работа", "progress", "прогресс",
    "ongoing", "текущий", "unfinished", "незавершённый", "draft", "черновик",
    "sketch", "эскиз", "developing", "разработка", "building", "строительство",
    "creating", "создание", "working", "работающий", "evolving", "эволюция",
    "under construction", "в строительстве", "incomplete", "неполный",
    "partial", "частичный", "preliminary", "предварительный", "starting",
    "начало", "beginning", "начало", "development", "развитие", "process",
    "процесс", "stage", "этап", "phase", "фаза", "initial", "первоначальный",
    "rough", "грубый", "unpolished", "необработанный", "raw", "сырой", "trial",
    "пробный", "experiment", "эксперимент", "test", "тест", "prototype",
    "прототип", "drafting", "черчение", "designing", "дизайнинг", "shaping",
    "формирование", "forming", "формирование", "modifying", "модификация",
    "adjusting", "настройка", "refining", "уточнение", "improving",
    "улучшение", "evolving", "развивающийся", "changing", "изменение",
    "updating", "обновление", "editing", "редактирование", "revision",
    "ревизия", "iteration", "итерация", "step", "шаг", "progression",
    "продвижение", "evolution", "эволюция", "growth", "рост", "transformation",
    "трансформация", "adaptation", "адаптация", "modification", "модификация",
    "construction", "строительство", "assembly", "сборка", "crafting",
    "изготовление", "building", "строительство", "design", "дизайн",
    "creation", "создание", "work in progress", "работа в процессе",
    "underway", "в процессе", "pending", "в ожидании", "in motion",
    "в движении", "develop", "развивать", "shape", "формировать", "mold",
    "лепить", "craft", "создавать", "forge", "ковать", "build", "строить",
    "advance", "продвигать", "refine", "совершенствовать", "process video",
    "видео процесса", "making", "создание", "recording", "запись", "live",
    "прямой эфир", "work in action", "работа в действии", "sleeve in progress",
    "рукав в процессе", "ongoing work", "текущая работа", "tattooing",
    "татуирование", "in session", "в сеансе", "working on", "работаю над"
]

# Ключевые слова для категории "equipment"
equipment_keywords = [
    "equipment", "оборудование", "machine", "машинка", "needle", "игла", "gun",
    "пистолет", "ink", "чернила", "power supply", "блок питания", "clip cord",
    "шнур", "foot pedal", "педаль", "tube", "трубка", "grip", "хват", "tip",
    "наконечник", "cartridge", "картридж", "disposable", "одноразовый",
    "sterile", "стерильный", "latex", "латекс", "gloves", "перчатки", "mask",
    "маска", "apron", "фартук", "razor", "бритва", "stencil", "трафарет",
    "paper", "бумага", "transfer", "перенос", "spirit", "спирт", "green soap",
    "зелёное мыло", "vaseline", "вазелин", "petroleum", "петролатум", "cream",
    "крем", "lotion", "лосьон", "aftercare", "послеуход", "tool", "инструмент",
    "device", "устройство", "supply", "поставка", "kit", "набор", "set",
    "набор", "accessory", "аксессуар", "part", "часть", "component",
    "компонент", "material", "материал", "ink cap", "чернильная чашка",
    "container", "контейнер", "bottle", "бутылка", "spray", "спрей", "cleaner",
    "очиститель", "disinfectant", "дезинфицирующее", "alcohol", "спирт",
    "cotton", "ватный", "pad", "тампон", "wipe", "салфетка", "bag", "пакет",
    "box", "коробка", "stand", "стойка", "holder", "держатель", "clamp",
    "зажим", "cable", "кабель", "plug", "вилка", "switch", "переключатель",
    "battery", "батарея", "charger", "зарядное", "motor", "мотор", "blade",
    "лезвие", "handle", "ручка", "base", "основа", "frame", "рама", "support",
    "поддержка", "platform", "платформа", "station", "станция", "unit", "блок",
    "system", "система", "gear", "механизм", "fixture", "приспособление",
    "attachment", "приставка", "adapter", "адаптер", "connector",
    "соединитель", "hose", "шланг", "pump", "насос", "filter", "фильтр",
    "cover", "крышка", "lid", "крышка", "seal", "уплотнение"
]

# Ключевые слова для категории "appointment"
appointment_keywords = [
    "appointment",
    "запись",
    "schedule",
    "расписание",
    "booking",
    "бронирование",
    "free slot",
    "свободное место",
    "available",
    "доступно",
    "open slot",
    "открытое место",
    "calendar",
    "календарь",
    "time slot",
    "временной слот",
    "reservation",
    "резервирование",
    "sign up",
    "записаться",
    "book a session",
    "забронировать сеанс",
    "free time",
    "свободное время",
    "availability",
    "доступность",
    "open for booking",
    "открыто для брони",
    "schedule a session",
    "запланировать сеанс",
    "recording",
    "запись на сеанс",
    "session booking",
    "бронирование сеанса",
    "free spot",
    "свободное место",
    "open for appointments",
    "открыто для записи",
    "appointment available",
    "запись доступна",
    "book now",
    "бронируй сейчас",
    "reserve",
    "резерв",
    "time available",
    "время доступно",
    "schedule open",
    "расписание открыто",
    "appointment slot",
    "слот для записи",
    "booking open",
    "бронирование открыто",
    "session available",
    "сеанс доступен",
    "free appointment",
    "свободная запись",
    "schedule update",
    "обновление расписания",
    "new slots",
    "новые слоты",
    "open time",
    "открытое время",
    "book your spot",
    "забронируй своё место",
    "appointment time",
    "время записи",
    "schedule now",
    "планируй сейчас",
    # Добавляем слова, связанные с календарями и датами
    "january",
    "february",
    "march",
    "april",
    "may",
    "june",
    "july",
    "august",
    "september",
    "october",
    "november",
    "december",
    "январь",
    "февраль",
    "март",
    "апрель",
    "май",
    "июнь",
    "июль",
    "август",
    "сентябрь",
    "октябрь",
    "ноябрь",
    "декабрь",
    "month",
    "месяц",
    "dates",
    "даты",
    "days",
    "дни",
    "marked",
    "пометка",
    "availability calendar",
    "календарь доступности",
    "schedule calendar",
    "календарь расписания",
    "booking calendar",
    "календарь бронирования",
    "free dates",
    "свободные даты",
    "open dates",
    "открытые даты",
    "calendar update",
    "обновление календаря",
    "month schedule",
    "расписание месяца"
]

# Ключевые слова для категории "equipment_and_studio"
equipment_and_studio_keywords = [
    "equipment", "оборудование", "machine", "машинка", "needle", "игла", "gun",
    "пистолет", "ink", "чернила", "power supply", "блок питания", "clip cord",
    "шнур", "foot pedal", "педаль", "tube", "трубка", "grip", "хват", "tip",
    "наконечник", "cartridge", "картридж", "disposable", "одноразовый",
    "sterile", "стерильный", "latex", "латекс", "gloves", "перчатки", "mask",
    "маска", "apron", "фартук", "razor", "бритва", "stencil", "трафарет",
    "paper", "бумага", "transfer", "перенос", "spirit", "спирт", "green soap",
    "зелёное мыло", "vaseline", "вазелин", "petroleum", "петролатум", "cream",
    "крем", "lotion", "лосьон", "aftercare", "послеуход", "tool", "инструмент",
    "device", "устройство", "supply", "поставка", "kit", "набор", "set",
    "набор", "accessory", "аксессуар", "part", "часть", "component",
    "компонент", "material", "материал", "ink cap", "чернильная чашка",
    "container", "контейнер", "bottle", "бутылка", "spray", "спрей", "cleaner",
    "очиститель", "disinfectant", "дезинфицирующее", "alcohol", "спирт",
    "cotton", "ватный", "pad", "тампон", "wipe", "салфетка", "bag", "пакет",
    "box", "коробка", "stand", "стойка", "holder", "держатель", "clamp",
    "зажим", "cable", "кабель", "plug", "вилка", "switch", "переключатель",
    "battery", "батарея", "charger", "зарядное", "motor", "мотор", "blade",
    "лезвие", "handle", "ручка", "base", "основа", "frame", "рама", "support",
    "поддержка", "platform", "платформа", "station", "станция", "unit", "блок",
    "system", "система", "gear", "механизм", "fixture", "приспособление",
    "attachment", "приставка", "adapter", "адаптер", "connector",
    "соединитель", "hose", "шланг", "pump", "насос", "filter", "фильтр",
    "cover", "крышка", "lid", "крышка", "seal", "уплотнение", "studio",
    "студия", "upgrade", "улучшение", "renovation", "ремонт", "cleaning",
    "уборка", "design", "дизайн студии", "atmosphere", "атмосфера", "interior",
    "интерьер", "team", "команда", "collective", "коллектив", "improvement",
    "совершенствование", "redecoration", "перепланировка", "setup",
    "настройка", "organization", "организация", "workspace", "рабочее место",
    "enhancement", "усовершенствование", "video tour", "видео тур",
    "studio tour", "тур по студии"
]
