- name: Debug environment
  run: |
    echo "VK_TOKEN: $VK_TOKEN"
    echo "TELEGRAM_TOKEN: $TELEGRAM_TOKEN"
    echo "GROUP_ID: $GROUP_ID"
    echo "CHAT_ID_TRACKING: $CHAT_ID_TRACKING"
    echo "CHAT_ID_HER: $CHAT_ID_HER"
    echo "HF_TOKEN: $HF_TOKEN"
    echo "YNDX_API_KEY: $YNDX_API_KEY"
    echo "GITHUB_TOKEN: $GITHUB_TOKEN"
  env:
    VK_TOKEN: ${{ secrets.VK_TOKEN }}
    TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
    GROUP_ID: ${{ secrets.GROUP_ID }}
    CHAT_ID_TRACKING: ${{ secrets.CHAT_ID_TRACKING }}
    CHAT_ID_HER: ${{ secrets.CHAT_ID_HER }}
    HF_TOKEN: ${{ secrets.HF_TOKEN }}
    YNDX_API_KEY: ${{ secrets.YNDX_API_KEY }}
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
