name: Bot Workflow

on:
  schedule:
    - cron: '*/5 * * * *'  # Проверка каждые 5 минут (можно настроить реже, если не нужно так часто)
  workflow_dispatch:
    inputs:
      compliment-type:
        description: 'Type of compliment to send (optional)'
        required: false
        default: ''
        options:
          - ''
          - weekly
          - client_interactions
          - tattoo_ideas
          - equipment_and_studio

jobs:
  bot:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
        with:
          repository: NEFORMOT/vk-telegram-bot
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run bot
        run: |
          python bot.py ${{ github.event.inputs.compliment-type && '--compliment-type ' + github.event.inputs.compliment-type || '' }}
        env:
          VK_TOKEN: ${{ secrets.VK_TOKEN }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          GROUP_ID: ${{ secrets.GROUP_ID }}
          CHAT_ID_TRACKING: ${{ secrets.CHAT_ID_TRACKING }}
          CHAT_ID_HER: ${{ secrets.CHAT_ID_HER }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          YNDX_API_KEY: ${{ secrets.YNDX_API_KEY }}
      - name: Commit state
        run: |
          git config --global user.email "bot@example.com"
          git config --global user.name "Bot"
          git add state.json || echo "No state.json to add"
          git commit -m "Update state.json" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
